read.tab("Data//body_dim_long.tab",header=TRUE)
read.table("Data//body_dim_long.tab",header=TRUE)
d <- read.table("Data//body_dim_long.tab",header=TRUE)
d
summary(d)
as.factor(d$subj)
d$subj <- as.factor(d$subj)
summary(d)
hist(d$height)
hist(d$height)
hist(d$weight)
?hist
range(d$weight)
diff(range(d$weight))
hist(d$weight,breaks=45)
plot(density(d$weight))
women <- subset(d, sex=="f")
summary(women)
summary(women)
hist(women$weight)
hist(women$weight)
hist(women$weight,breaks=diff(range(women$weight)))
density(women$weight)
plot(density(women$weight))
ggplot(data=d) + geom_density(aes(x=weight))
library(ggplot2)
ggplot(data=d) + geom_density(aes(x=weight))
ggplot(data=d) + geom_density(aes(x=weight,color=sex))
ggplot(data=d) + geom_histogram(aes(x=weight,color=sex))
ggplot(data=d) + geom_histogram(aes(x=weight))
ggplot(data=d) + geom_histogram(aes(x=weight),fill="white")
ggplot(data=d) + geom_histogram(aes(x=weight),fill="white",color="black")
ggplot(data=d) + geom_histogram(aes(x=weight),fill="white",color="black") + geom_density(aes(x=weight))
ggplot(data=d) + geom_histogram(aes(x=weight,y=..density..),fill="white",color="black") + geom_density(aes(x=weight))
ggplot(data=d,aes(x=weight)) + geom_histogram(aes(y=..density..),fill="white",color="black") + geom_density()
ggplot(data=d,aes(x=weight)) + geom_histogram(aes(y=..density..),fill="white",color="black") + geom_density(fill="lightblue")
ggplot(data=d,aes(x=weight)) + geom_histogram(aes(y=..density..),fill="white",color="black") + geom_density(fill="lightblue",alpha=.2)
ggplot(data=d,aes(x=weight)) + geom_histogram(aes(y=..density..),fill="white",color="black") + geom_density(fill="lightblue",alpha=.6)
ggplot(data=d) + geom_density(aes(x=height,color=sex))
ggplot(data=d) + geom_density(aes(x=height,color=sex,fill=sex))
ggplot(data=d) + geom_density(aes(x=height,color=sex,fill=sex),alpha=0.6)
