priming <- read.table("Data/priming.tab",header = T)
priming$subj <- as.factor(priming$subj)
priming <- subset(priming, item <= 20) # Filler ausschließen
priming$item <- as.factor(priming$item)
priming
head(priming)
library(ggplot2)
ggplot(priming) + geom_jitter(aes(x=cond,y=RT))
aggregate(RT ~ prime*target,data=priming,mean)
library(ez)
?ezStats
ezStats(priming,dv=.(RT),wid=.(subj),within=.(prime,target))
ezStats(priming,dv=.(RT),wid=.(item),within=.(prime,target))
ezStats(priming,dv=.(RT),wid=.(subj),within=.(cond))
priming.by.subject <- aggregate(RT ~ cond * subj,data=priming,FUN = mean)
primimg.by.subject
priming.by.subject
head(priming.by.subject)
priming.by.subject <- aggregate(RT ~ prime* target * subj,data=priming,FUN = mean)
head(priming.by.subject)
priming.by.subject <- aggregate(RT ~ cond * subj,data=priming,FUN = mean)
ggplot(priming.by.subject) + geom_jitter(aes(x=cond,y=RT))
?geom_jitter
?geom_jitter
ggplot(priming.by.subject) + geom_jitter(aes(x=cond,y=RT),position=position_jitter(width=.1))
ggplot(priming.by.subject) + geom_jitter(aes(x=cond,y=RT),position=position_jitter(width=0))
ggplot(priming.by.subject) + geom_point(aes(x=cond,y=RT))
ggplot(priming.by.subject) + geom_point(aes(x=cond,y=RT),alpha=0.2)
ggplot(priming.by.subject) + geom_point(aes(x=cond,y=RT),alpha=0.5)
ggplot(priming) + geom_point(aes(x=cond,y=RT),alpha=0.5)
ggplot(priming) + geom_point(aes(x=cond,y=RT),alpha=0.2)
priming.by.subject <- aggregate(RT ~ prime * target * subj,data=priming,FUN = mean)
ggplot(priming.by.subject) + geom_point(aes(x=target,y=RT,color=prime),alpha=0.2)
ggplot(priming.by.subject) + geom_point(aes(x=target,y=RT,color=prime))
ezStats(priming,dv=.(RT),wid=.(subj),within=.(prime,target))
ezANOVA(priming,dv=.(RT),wid=.(subj),within=.(prime,target))
ezANOVA(priming,dv=.(RT),wid=.(subj),within=.(cond))
ezANOVA(priming,dv=.(RT),wid=.(subj),within=.(prime,target))
ezANOVA(priming,dv=.(RT),wid=.(subj),within=.(prime,target),detailed=TRUE)
aphasiker <- read.csv2("Data/aphasiker.csv",header = T)
aphasiker <- na.omit(aphasiker)
rt <- read.table("Data/punkt_rt.tab",header = T)
rt$subj <- as.factor(rt$subj)
ggplot(aphasiker,aes(x=Aphasie,y=Lex_Dec)) + geom_point(aes(color=Aphasie)) + geom_smooth(aes(x=as.numeric(Aphasie),y=Lex_Dec),method="lm", se=FALSE,color="red")
summary(aov(Lex_Dec ~ Aphasie,data=aphasiker))
summary(lm(Lex_Dec ~ Aphasie,data=aphasiker))
aov
ezANOVA(priming,dv=.(RT),wid=.(subj),within=.(prime,target),detailed=TRUE)
ezANOVA(priming,dv=.(RT),wid=.(subj),within=.(prime,target))
ezANOVA(priming,dv=.(RT),wid=.(item),within=.(prime,target))
ezANOVA(subset(priming,target=="E"),dv=.(RT),wid=.(subj),within=.(prime))
ezANOVA(subset(priming,target=="D"),dv=.(RT),wid=.(subj),within=.(prime))
ezANOVA(priming,dv=.(RT),wid=.(item),within=.(prime,target))
ezANOVA(priming,dv=.(RT),wid=.(item),within=.(prime))
ezANOVA(priming,dv=.(RT),wid=.(item),within=.(prime),within_full=.(prime,target))
ezANOVA(subset(priming,target=="D"),dv=.(RT),wid=.(subj),within=.(prime))
head(priming)
ezANOVA(priming,dv=.(correct),wid=.(item),within=.(prime,target))
priming$correct <- as.numeric(priming$correct)
ezANOVA(priming,dv=.(correct),wid=.(item),within=.(prime,target))
ezANOVA(subset(priming,target=="D",dv=.(correct),wid=.(item),within=.(prime)))
ezANOVA(subset(priming,target=="D"),dv=.(correct),wid=.(item),within=.(prime)))
ezANOVA(subset(priming,target=="D"),dv=.(correct),wid=.(item),within=.(prime))
ezANOVA(subset(priming,target=="E"),dv=.(correct),wid=.(item),within=.(prime))
head(priming)
priming$correct <- as.logical(priming$correct)
head(priming)
ezANOVA(priming,dv=.(RT),wid=.(item),within=.(prime,target))
ezANOVA(subset(priming,correct),dv=.(RT),wid=.(item),within=.(prime,target))
