?women
lmU()
lm(weight ~  height, women)
summary(lm(weight ~  height, women))
summary(lm(height ~  weight, women))
1 / 3.45
library(ggplot2)
ggplot(women,aes(x=height,y=weight)) + geom_point() + geom_smooth(method="lm")
body <- read.table("Data/body_dim_long.tab",header=TRUE)
head(body)
ggplot(body,aes(x=sex,y=weight)) + geom_point() + geom_smooth(method="lm")
ggplot(body,aes(x=sex,y=weight)) + geom_point()
summary(lm(weight~sex,body))
summary(aov(weight~sex,body))
?factor
?refactor
factor(body$sex, levels=c("m","f")
)
body$sex <- factor(body$sex, levels=c("m","f"))
summary(lm(weight~sex,body))
head(body)
summary(lm(weight~height + age,body))
summary(lm(weight~age + height,body))
summary(lm(weight~height + age,body))
summary(lm(weight~height + age,body))
summary(lm(weight~height * age,body))
ggplot(body,aes(x=height,y=weight,color=factor(age))) + geom_point() + geom_smooth()
ggplot(body,aes(x=height,y=weight,color=age()) + geom_point() + geom_smooth()
)
ggplot(body,aes(x=height,y=weight,color=age())) + geom_point() + geom_smooth()
ggplot(body,aes(x=height,y=weight,color=age)) + geom_point() + geom_smooth()
ggplot(body,aes(x=height,y=weight,color=sex)) + geom_point() + geom_smooth()
ggplot(body,aes(x=height,y=weight,color=sex)) + geom_point() + geom_smooth(method="lm")
summary(lm(weight~height * sex,body))
aphasiker <- read.csv2("Data//aphasiker.csv")
head(aphasiker)
levels(aphasiker$Aphasie)
summary(lm(Lex_Dec ~  Aphasie,data=aphasiker))
summary(aov(Lex_Dec ~  Aphasie,data=aphasiker))
factor(aphasiker$Aphasie,levels=c("C","A","B","W")
)
aphasiker$Aphasie <- factor(aphasiker$Aphasie,levels=c("C","A","B","W"))
summary(lm(Lex_Dec ~  Aphasie,data=aphasiker))
aphasiker$Aphasie <- factor(aphasiker$Aphasie)
summary(lm(Lex_Dec ~  Aphasie,data=aphasiker))
aphasiker$Aphasie <- factor(as.character(aphasiker$Aphasie))
summary(lm(Lex_Dec ~  Aphasie,data=aphasiker))
ggplot(aphasie,aes(y=Lex_Dec,x=aphasie)) + geom_point() + geom_smooth(method="lm")
ggplot(aphasiker,aes(y=Lex_Dec,x=aphasie)) + geom_point() + geom_smooth(method="lm")
ggplot(aphasiker,aes(y=Lex_Dec,x=Aphasie)) + geom_point() + geom_smooth(method="lm")
lm(weight ~ height, women)
plot(lm(weight ~ height, women))
plot(lm(weight ~ height, women))
ggplot(body,aes(x=height,y=weight)) + geom_point() + geom_smooth()
ggplot(body,aes(x=height,y=weight)) + geom_point() + geom_smooth(method="lm")
confint(lm(weight ~ height, women))
?confint
confint(lm(weight ~ height, women),level=0.99)
