library(lme4)
summary(lm(Reaction ~ Days,data=sleepstudy))
summary(lm(Reaction ~ 1 + Days,data=sleepstudy))
summary(lm(Reaction ~ 0 + Days,data=sleepstudy))
summary(lm(Reaction ~ 1 + I(scale(Days,scale = FALSE)),data=sleepstudy))
summary(lm(Reaction ~ Days,data=sleepstudy))
sleep.lmer <- lmer(Reaction ~ Days + (1|Subject), data=sleepstudy)
summary(sleep.lmer)
sleep.lmer.slopes <- lmer(Reaction ~ Days + (1+Days|Subject), data=sleepstudy)
summary(sleep.lmer.slopes)
anova(sleep.lmer,sleep.lmer.slopes)
sleep.lmer.slopes <- lmer(Reaction ~ Days + (1+Days|Subject), data=sleepstudy, REML=FALSE)
sleep.lmer <- lmer(Reaction ~ Days + (1|Subject), data=sleepstudy, REML=FALSE)
anova(sleep.lmer,sleep.lmer.slopes)
anova(sleep.lmer.slopes,sleep.lmer)
sleep.lmer.slopes.int <- lmer(Reaction ~ Days + (1|Subject) + (0 +Days|Subject), data=sleepstudy, REML=FALSE)
anova(sleep.lmer.slopes,sleep.lmer.slopes.int)
anova(sleep.lmer.slopes,sleep.lmer.slopes.int)
suppressPackageStartupMessages(library(ez))
+                     return_aov=TRUE)
sleep.ez <- ezANOVA(sleepstudy,dv=.(Reaction),wid=.(Subject),within=.(Days),detailed=TRUE,return_aov=TRUE)
sleep.ez$ANOVA
warnings()
